version: '3.8'
services:
  app:
    image: admin_kaltengventura-web
    front:
      networks:
        - admin_web
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"

networks:
  admin_web:
    driver: bridge