version: '3'
services:
  frontend:
    image: admin_kaltengventura-web
    networks:
      - custom_network
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
  api:
    image: api-kaltengventura-api
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge